/**
 * fxShare.ts — typed access to the adjudicated DSA FX-share dataset.
 *
 * The dataset (src/data/fx-share.json) is generated by
 * scripts/build-fx-share.mjs from a verbatim copy of the TEA-878
 * adjudication package's proposed-corrected-dataset.csv. Each entry is the
 * foreign-currency share of public debt at the latest actual year reported
 * in that country's most recent published IMF DSA, with full provenance
 * (report URL, PDF page, table reference) and the two classification
 * dimensions an IMF reader will ask about first: definition basis
 * (currency vs residency) and debt perimeter.
 *
 * Countries WITHOUT an entry keep the historical default of 0 percent.
 * That zero is an UNSOURCED FALLBACK, not data — the UI and methodology
 * page must label it as such (TEA-880, transparency request from IMF SPR).
 */
import fxShareData from './data/fx-share.json';

export interface FxShareEntry {
  /** FX share of public debt, percent of total debt (0-100). */
  valuePct: number;
  /** Reference year as printed in the source report (may be a fiscal-year label). */
  year: string;
  framework: 'LIC_DSF' | 'MAC_SRDSF';
  /** 'currency' = denomination-based; 'residency' = external-debt proxy. */
  definitionBasis: 'currency' | 'residency';
  debtPerimeter: string;
  isProxy: boolean;
  proxySource: string | null;
  confidence: string;
  reportTitle: string;
  reportDate: string;
  publicationUrl: string;
  pdfPage: string;
  printedPage: string | null;
  tableRef: string;
}

interface FxShareFile {
  _meta: {
    row_count: number;
    coverage: Record<string, number>;
    source_csv_sha256: string;
  } & Record<string, unknown>;
  countries: Record<string, FxShareEntry>;
}

const DATA = fxShareData as unknown as FxShareFile;

/** Dataset-level metadata (row count, coverage, source hash). */
export const FX_SHARE_META = DATA._meta;

/**
 * Look up the sourced FX-share entry for a country (ISO-3, any case).
 * Returns undefined when the country has no adjudicated value — callers
 * must then treat the 0-percent default as an unsourced fallback and say so.
 */
export function getFxShare(iso: string): FxShareEntry | undefined {
  return DATA.countries[iso.toLowerCase()];
}

/** Human-readable label for the debt perimeter codes used in the dataset. */
export function perimeterLabel(code: string): string {
  switch (code) {
    case 'central_government':
      return 'central government';
    case 'general_government':
      return 'general government';
    case 'public_sector':
      return 'public sector';
    case 'nfps':
      return 'non-financial public sector';
    default:
      return code.replace(/_/g, ' ');
  }
}

/** Short framework label for UI text. */
export function frameworkLabel(fw: FxShareEntry['framework']): string {
  return fw === 'LIC_DSF' ? 'LIC-DSF' : 'SRDSF';
}
