/**
 * fxShare.ts — typed access to the adjudicated DSA FX-share dataset.
 *
 * The dataset (src/data/fx-share.json) is generated by
 * scripts/build-fx-share.mjs from a verbatim copy of the TEA-878
 * adjudication package's proposed-corrected-dataset.csv. Each entry is the
 * foreign-currency share of public debt at the latest actual year reported
 * in that country's most recent published IMF DSA, with full provenance
 * (report URL, PDF page, table reference) and the two classification
 * dimensions an IMF reader will ask about first: definition basis
 * (currency vs residency) and debt perimeter.
 *
 * Missing source coverage and an observed zero are different facts. The
 * lookup layer therefore returns a discriminated coverage state. A separate
 * default-resolution step may apply a tagged 0 percent model fallback so the
 * calculator can run, but it never turns missing coverage into an observation.
 */
import fxShareData from './data/fx-share.json';
import type { CountryState } from './types';

export interface FxShareDerivation {
  /** How the share was obtained from the cited page. */
  kind: 'ratio' | 'figure' | 'direct';
  /** FX-denominated (or external) debt, percent of GDP, as used in the ratio. */
  numeratorPctGdp: number | null;
  /** Total public debt, percent of GDP, as used in the ratio. */
  denominatorPctGdp: number | null;
  /** The share as printed verbatim on the page (direct statements). */
  printedSharePct: number | null;
  note: string | null;
}

export interface FxShareAudit {
  /** Outcome of the 2026-07-23 independent source-page audit. */
  outcome: 'CONFIRMED' | 'CONFIRMED_APPROX' | 'CORRECTED';
  date: string;
  /** The auditor's own chart measurement, where it differs meaningfully. */
  independentValuePct: number | null;
  /** True where the citation (page/file hash) was repaired to the adjudicated final. */
  provenanceFixed: boolean;
  note: string | null;
}

export interface FxShareEntry {
  /** FX share of public debt, percent of total debt (0-100). */
  valuePct: number;
  /** Reference year as printed in the source report (may be a fiscal-year label). */
  year: string;
  /** Whether the source column/point is a hard actual or a staff estimate. */
  yearStatus: 'actual' | 'estimate';
  framework: 'LIC_DSF' | 'MAC_SRDSF';
  /** 'currency' = denomination-based; 'residency' = external-debt proxy. */
  definitionBasis: 'currency' | 'residency';
  debtPerimeter: string;
  isProxy: boolean;
  proxySource: string | null;
  confidence: string;
  /** Carrier of the observation on the cited page. */
  extractionMethod: 'table' | 'text' | 'figure';
  derivation: FxShareDerivation;
  audit: FxShareAudit;
  /** Latest hard-actual alternative where the shipped value is an estimate. */
  latestActualAlternativePct: number | null;
  reportTitle: string;
  reportDate: string;
  publicationUrl: string;
  pdfPage: string;
  printedPage: string | null;
  tableRef: string;
}

export interface ObservedFxShareCoverage {
  kind: 'observed';
  iso: string;
  sourceValuePct: number;
  entry: FxShareEntry;
}

export interface MissingFxShareCoverage {
  kind: 'missing';
  iso: string;
  /** A missing source value stays missing at the data boundary. */
  sourceValuePct: null;
  reason: 'missing_source_coverage';
}

export type FxShareCoverage =
  | ObservedFxShareCoverage
  | MissingFxShareCoverage;

export interface ObservedFxShareDefault {
  kind: 'observed';
  iso: string;
  sourceValuePct: number;
  modelValuePct: number;
  observedZero: boolean;
  usesFallback: false;
  entry: FxShareEntry;
}

export interface FallbackFxShareDefault {
  kind: 'fallback';
  iso: string;
  /** The economic fact remains unavailable. */
  sourceValuePct: null;
  /** Separate calculation assumption used only to keep the model runnable. */
  modelValuePct: 0;
  observedZero: false;
  usesFallback: true;
  reason: 'missing_source_coverage';
}

export type FxShareDefaultState =
  | ObservedFxShareDefault
  | FallbackFxShareDefault;

export type FxShareScenarioState =
  | { kind: 'sourced_default'; defaultState: ObservedFxShareDefault }
  | { kind: 'observed_zero_default'; defaultState: ObservedFxShareDefault }
  | { kind: 'fallback_default'; defaultState: FallbackFxShareDefault }
  | {
      kind: 'user_defined';
      defaultState: FxShareDefaultState;
      allValuesZero: boolean;
    };

interface FxShareFile {
  _meta: {
    row_count: number;
    coverage: Record<string, number>;
    source_csv_sha256: string;
  } & Record<string, unknown>;
  countries: Record<string, FxShareEntry>;
}

const DATA = fxShareData as unknown as FxShareFile;

/** Dataset-level metadata (row count, coverage, source hash). */
export const FX_SHARE_META = DATA._meta;

/** Load source coverage without manufacturing a numeric value for a gap. */
export function getFxShareCoverage(isoValue: string): FxShareCoverage {
  const iso = isoValue.toLowerCase();
  const entry = DATA.countries[iso];
  if (entry) {
    return {
      kind: 'observed',
      iso,
      sourceValuePct: entry.valuePct,
      entry,
    };
  }
  return {
    kind: 'missing',
    iso,
    sourceValuePct: null,
    reason: 'missing_source_coverage',
  };
}

/** Resolve a model default while retaining the source-coverage state. */
export function resolveFxShareDefault(
  coverage: FxShareCoverage,
): FxShareDefaultState {
  if (coverage.kind === 'observed') {
    return {
      kind: 'observed',
      iso: coverage.iso,
      sourceValuePct: coverage.sourceValuePct,
      modelValuePct: coverage.sourceValuePct,
      observedZero: coverage.sourceValuePct === 0,
      usesFallback: false,
      entry: coverage.entry,
    };
  }
  return {
    kind: 'fallback',
    iso: coverage.iso,
    sourceValuePct: null,
    modelValuePct: 0,
    observedZero: false,
    usesFallback: true,
    reason: coverage.reason,
  };
}

export function getFxShareDefault(iso: string): FxShareDefaultState {
  return resolveFxShareDefault(getFxShareCoverage(iso));
}

/** Backward-compatible sourced-entry lookup. Prefer the typed coverage API. */
export function getFxShare(iso: string): FxShareEntry | undefined {
  const coverage = getFxShareCoverage(iso);
  return coverage.kind === 'observed' ? coverage.entry : undefined;
}

/**
 * Apply the resolved state to every numeric engine path and attach the state
 * to the country so downstream transformations never infer provenance from 0.
 */
export function applyFxShareDefault(
  country: CountryState,
  defaultState: FxShareDefaultState,
): CountryState {
  const valuePct = defaultState.modelValuePct;
  return {
    ...country,
    fxShareDefault: defaultState,
    defaults: { ...country.defaults, fcuShare: valuePct },
    historicalFcuShare: valuePct,
    yearlyDefaults: country.yearlyDefaults
      ? {
          ...country.yearlyDefaults,
          fcuShare: country.yearlyDefaults.fcuShare.map(() => valuePct),
        }
      : country.yearlyDefaults,
  };
}

/** Classify the current scenario without losing the tagged default state. */
export function getFxShareScenarioState(
  defaultState: FxShareDefaultState,
  values: number[],
): FxShareScenarioState {
  const usesDefault =
    values.length > 0 &&
    values.every(value => Math.abs(value - defaultState.modelValuePct) < 1e-9);
  if (!usesDefault) {
    return {
      kind: 'user_defined',
      defaultState,
      allValuesZero: values.length > 0 && values.every(value => value === 0),
    };
  }
  if (defaultState.kind === 'fallback') {
    return { kind: 'fallback_default', defaultState };
  }
  if (defaultState.observedZero) {
    return { kind: 'observed_zero_default', defaultState };
  }
  return { kind: 'sourced_default', defaultState };
}

/** Human-readable label for the debt perimeter codes used in the dataset. */
export function perimeterLabel(code: string): string {
  switch (code) {
    case 'central_government':
      return 'central government';
    case 'general_government':
      return 'general government';
    case 'public_sector':
      return 'public sector';
    case 'nfps':
      return 'non-financial public sector';
    default:
      return code.replace(/_/g, ' ');
  }
}

/** Short framework label for UI text. */
export function frameworkLabel(fw: FxShareEntry['framework']): string {
  return fw === 'LIC_DSF' ? 'LIC-DSF' : 'SRDSF';
}

/**
 * Display form of a sourced share, honest about instrument precision:
 * chart-derived values are estimates, so they render as approximate
 * integers; table and text values keep one decimal.
 */
export function formatFxShareValue(entry: FxShareEntry): string {
  if (entry.extractionMethod === 'figure') {
    if (entry.valuePct > 0 && entry.valuePct < 0.75) return '<1%';
    return `≈${Math.round(entry.valuePct)}%`;
  }
  return `${entry.valuePct.toFixed(1)}%`;
}

/** One-decimal percent for derivation text (numerators/denominators). */
function pct(n: number): string {
  return Number.isInteger(n) ? String(n) : n.toFixed(1).replace(/\.0$/, '');
}

/**
 * Human-readable derivation sentence: the exact arithmetic connecting the
 * displayed share to the numbers a reader will find on the cited page.
 */
export function derivationSentence(entry: FxShareEntry): string {
  const d = entry.derivation;
  const share = formatFxShareValue(entry);
  if (d.kind === 'direct' && d.printedSharePct != null) {
    return `The report states the share directly on the cited page: ${pct(d.printedSharePct)}% of total debt.`;
  }
  if (d.kind === 'ratio' && d.numeratorPctGdp != null && d.denominatorPctGdp != null) {
    const numLabel =
      entry.definitionBasis === 'currency' ? 'FX-denominated debt' : 'external debt';
    return (
      `Derivation: ${numLabel} ${pct(d.numeratorPctGdp)} ÷ total public debt ` +
      `${pct(d.denominatorPctGdp)}, both percent of GDP as printed on the cited page, ` +
      `= ${share} of total debt.`
    );
  }
  if (d.kind === 'figure') {
    if (d.numeratorPctGdp != null && d.denominatorPctGdp != null) {
      return (
        `Derivation: read from the report's Debt-by-Currency chart at the ${entry.year} point, ` +
        `foreign currency ≈${pct(d.numeratorPctGdp)} ÷ total ≈${pct(d.denominatorPctGdp)} ` +
        `(percent of GDP) = ${share} of total debt; chart-derived estimate.`
      );
    }
    return (
      `Read from the report's Debt-by-Currency chart at the ${entry.year} point; ` +
      'chart-derived estimate.'
    );
  }
  return '';
}

/** Year-status clause, including the hard-actual alternative when known. */
export function yearStatusSentence(entry: FxShareEntry): string | null {
  if (entry.yearStatus !== 'estimate') return null;
  const alt =
    entry.latestActualAlternativePct != null
      ? ` The latest hard actual printed in the report implies ${entry.latestActualAlternativePct.toFixed(1)}%.`
      : '';
  return `The ${entry.year} observation is a staff estimate, the newest the DSA publishes.${alt}`;
}

/** One-line audit disclosure for the footnote. */
export function auditSentence(entry: FxShareEntry): string {
  if (entry.audit.outcome === 'CORRECTED') {
    return 'Corrected in the July 2026 independent audit after re-measuring the cited source; every cited page was re-read in that audit.';
  }
  return 'Independently re-verified against the cited page in the July 2026 audit.';
}
